# Netlify Configuration for Lengüitas Felices

[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "build"
  
  # Default build command
  command = "npm run build"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect rules for Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (if you want to use Netlify Forms)
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Environment variables for build optimization
[context.production.environment]
  REACT_APP_ENV = "production"
  GENERATE_SOURCEMAP = "false"

[context.deploy-preview.environment]
  REACT_APP_ENV = "staging"

[context.branch-deploy.environment]
  REACT_APP_ENV = "development"
